# Initial commands

# Routing commands
bestsave on C:\Documents and Settings\BlueDeep\Mis documentos\Orcad\Conector_PS2\Nueva carpeta\PS2-7.WRE
status_file C:\Documents and Settings\BlueDeep\Mis documentos\Orcad\Conector_PS2\Nueva carpeta\PS2-7.STS
bus diagonal
smart_route

# DFM commands

# Final commands
write routes C:\Documents and Settings\BlueDeep\Mis documentos\Orcad\Conector_PS2\Nueva carpeta\PS2-7.RTE
