# #####################################################################
# Automatically generated by qmake (2.01a) lun nov 1 09:22:57 2010
# #####################################################################
TEMPLATE = app
TARGET = simu_sie
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += csv.h \
    jz47xx_mmap.h \
    jz47xx_gpio.h \
    widgetdisplay.h
FORMS += csv.ui
SOURCES += csv.cpp \
    main.cpp \
    jz47xx_mmap.cpp \
    jz47xx_gpio.cpp \
    widgetdisplay.cpp
